name: homeDir

on:
  push:
    paths:
      - '.github/workflows/homeDir.yml'
      - 'homeDir/**'

env:
  NAME: homeDir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: |
          cd ${{ env.NAME }}
          go build -o ${{ env.NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ env.NAME }}
          files: ${{ env.NAME }}/${{ env.NAME }}
